export const SELECT_DATE = "SELECT_DATE";
export const CLICK_CELL = "CLICK_CELL";
export const RESET_SELECTED_DATE = "RESET_SELECTED_DATE";
export const SET_LOADING = "SET_LOADING";
export const SET_DATES = "SET_DATES";
export const SET_YEAR = "SET_YEAR";
export const SET_MONTH = "SET_MONTH";
export const SET_LAYOUT = "SET_LAYOUT";

export const FETCH_TASKS_FAILURE = "FETCH_TASKS_FAILURE";
export const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS";
export const FETCH_TASKS_REQUEST = "FETCH_TASKS_REQUEST";

export const SET_ALL_TASKS = "SET_ALL_TASKS";
export const UPDATE_TASKS = "UPDATE_TASKS";
